#!/bin/bash
set -x
set -eo pipefail

# s2i fails when /tmp/src/ is empty
mkdir -p /tmp/src
touch /tmp/src/.dummy

# We now run the assembly script. If there is a custom one written in the 
# source files, we use that instead.
if [ -f /opt/app-root/src/.s2i/bin/assemble ]; then
    /opt/app-root/src/.s2i/bin/assemble
else
    /usr/libexec/s2i/assemble
fi

# Restart application
# This is dumb way to restart, but it looks like supervisor doesn't have restart command
/var/lib/supervisord/bin/supervisord ctl stop run; /var/lib/supervisord/bin/supervisord ctl start run
